/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Check.Check;
import ConnectDatabase.DBConnect;
import Entity.NguoiDung;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ND
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public DoiMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jbdangnhap = new javax.swing.JButton();
        jbthoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmatkhaumoi = new javax.swing.JPasswordField();
        txtmatkhaucu = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(51, 84, 109));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đổi Mật Khẩu");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 400));
        setMinimumSize(new java.awt.Dimension(324, 282));
        setResizable(false);
        setSize(new java.awt.Dimension(374, 282));
        getContentPane().setLayout(null);

        jbdangnhap.setBackground(new java.awt.Color(255, 255, 255));
        jbdangnhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbdangnhap.setText("Đổi Mật Khẩu");
        jbdangnhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbdangnhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdangnhapActionPerformed(evt);
            }
        });
        jbdangnhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbdangnhapKeyReleased(evt);
            }
        });
        getContentPane().add(jbdangnhap);
        jbdangnhap.setBounds(20, 190, 120, 30);

        jbthoat.setBackground(new java.awt.Color(255, 255, 255));
        jbthoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbthoat.setText("Thoát");
        jbthoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbthoatActionPerformed(evt);
            }
        });
        getContentPane().add(jbthoat);
        jbthoat.setBounds(170, 190, 120, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doimatkhau2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/password.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 40, 40);

        jLabel4.setText("Mật Khẩu Cũ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 20, 70, 14);

        jLabel5.setText("Mật Khẩu Mới");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 90, 90, 14);

        txtmatkhaumoi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(37, 64, 91), 3, true));
        getContentPane().add(txtmatkhaumoi);
        txtmatkhaumoi.setBounds(50, 110, 230, 40);

        txtmatkhaucu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(37, 64, 91), 3, true));
        getContentPane().add(txtmatkhaucu);
        txtmatkhaucu.setBounds(50, 40, 230, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbdangnhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbdangnhapKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode()==evt.VK_ENTER) {
            send();
        }
    }//GEN-LAST:event_jbdangnhapKeyReleased

    private void jbdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdangnhapActionPerformed
        send();
    }//GEN-LAST:event_jbdangnhapActionPerformed

    private void jbthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbthoatActionPerformed
       dispose();      
    }//GEN-LAST:event_jbthoatActionPerformed
/*Code Here*/
    
    
     
    PreparedStatement ps = null;
    ResultSet rs= null;
    public void resetForm() {
        txtmatkhaumoi.setText("");
        txtmatkhaumoi.setText("");
        txtmatkhaumoi.requestFocus();
    }
public ArrayList<NguoiDung> findNguoiDung(String TenDangNhap) {
        ArrayList<NguoiDung> list = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        if (DBConnect.open()) {
            try {
                ps = DBConnect.cnn.prepareStatement("select * from tblNguoiDung where fldTenDangNhap = ?");
               ps.setString(1, MainAdmin.nameLogin);
                rs = ps.executeQuery();
                list = new ArrayList<NguoiDung>();
                while (rs.next()) {
                    NguoiDung nd = new NguoiDung();
                    nd.setTenDangNhap(rs.getString(1));
                    nd.setMatKhau(rs.getString(2));
                    
                    list.add(nd);
                }

            } catch (SQLException ex) {
               
            } finally {
                DBConnect.close(ps, rs);
            }
        }
        return list;
    }

    public void send() {
        String strnull = "";
       
        String pass1 = txtmatkhaucu.getText();
        String pass2 = txtmatkhaumoi.getText();
        ArrayList<NguoiDung> nd=new DoiMatKhau().findNguoiDung(Login.nameLogin);
        NguoiDung nguoiDung=new NguoiDung(Login.nameLogin, pass2);
        if (pass1.equals(strnull) || pass2.equals(strnull)) {
            JOptionPane.showMessageDialog(null, "Mật khẩu không được trống !");
            this.resetForm();
        } else if (DBConnect.open()) {
          
            if(pass1.equals(nd.get(0).getMatKhau())==false){
               JOptionPane.showMessageDialog(this, "Sai mật khẩu cũ "," Vui lòng kiểm tra lại",JOptionPane.INFORMATION_MESSAGE);
               txtmatkhaucu.requestFocus();
            }
            else
                if(txtmatkhaumoi.getText().length()<6&&!Check.checkNumber(pass2)){
                 JOptionPane.showMessageDialog(this, "Mật khẩu phải lớn hơn 5 ký tự "," Vui lòng kiểm tra lại",JOptionPane.INFORMATION_MESSAGE);
                 txtmatkhaumoi.requestFocus();
                }
            else
            {
            NguoiDung update = new DoiMatKhau().DoiMatKhau(nguoiDung);
             JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            }
        }

    }
    public NguoiDung DoiMatKhau(NguoiDung nd) {
        PreparedStatement ps = null;
        if (DBConnect.open()) {
            try {
                ps = DBConnect.cnn.prepareStatement("update tblNguoiDung set fldMatKhau = ? where fldTenDangNhap = ?");
               
                ps.setString(1, nd.getMatKhau());
                ps.setString(2, nd.getTenDangNhap());
                        
                int row = ps.executeUpdate();
                if (row < 1) {
                    nd = null;
                }
            } catch (SQLException ex) {
               
                nd = null;
            } finally {
                DBConnect.close();
            }
        }
        return nd;
    }

                                     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbdangnhap;
    private javax.swing.JButton jbthoat;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField txtmatkhaucu;
    private javax.swing.JPasswordField txtmatkhaumoi;
    // End of variables declaration//GEN-END:variables
}
