/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;




import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.DateFormat;
import java.util.Calendar;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
public class MainAdmin extends javax.swing.JFrame {

    public static String nameLogin;
    public static Date today = new Date();
    public static Locale local = new Locale("vi", "VI");
    public static DateFormat d = DateFormat.getDateInstance(DateFormat.MEDIUM, local);
    public static String date = d.format(today);
    

    /**
     * Creates new form Main
     */
    public MainAdmin() {
        initComponents();
        setUser();
        Timer dongho = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Calendar lich = Calendar.getInstance();
                int gio = lich.get(Calendar.HOUR);
                int phut = lich.get(Calendar.MINUTE);
                int giay = lich.get(Calendar.SECOND);
            }
        });
        dongho.start();
    }

    private void setUser() {
        nameLogin = Login.nameLogin;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpContent = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmHeThong = new javax.swing.JMenu();
        jmidoimatkhau = new javax.swing.JMenuItem();
        jmiLogOff = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmQuanLyKhoa = new javax.swing.JMenuItem();
        jmQuanLyChuyenNganh = new javax.swing.JMenuItem();
        jmQuanLyLop = new javax.swing.JMenuItem();
        jmTacVu = new javax.swing.JMenu();
        jmiNhapSV = new javax.swing.JMenuItem();
        jmiNhapGV = new javax.swing.JMenuItem();
        jmiNhapDiem = new javax.swing.JMenuItem();
        jmQuanLyHocPhan = new javax.swing.JMenuItem();
        jmQuanLyMonHoc = new javax.swing.JMenuItem();
        jmTimKiem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ TRƯỜNG ĐẠI HỌC");
        setMinimumSize(new java.awt.Dimension(1106, 700));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(1106, 700));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtpContent.setMinimumSize(new java.awt.Dimension(1106, 638));
        jtpContent.setPreferredSize(new java.awt.Dimension(1106, 638));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(102, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bia1.jpg"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtpContent.addTab("Trang Chủ", jPanel6);

        jMenuBar2.setBackground(new java.awt.Color(69, 82, 90));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar2.setToolTipText("");
        jMenuBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jmHeThong.setBackground(new java.awt.Color(94, 172, 175));
        jmHeThong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 82, 90)));
        jmHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/taikhoan.png"))); // NOI18N
        jmHeThong.setText("Tài Khoản");
        jmHeThong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jmHeThong.setPreferredSize(new java.awt.Dimension(145, 32));

        jmidoimatkhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmidoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doimatkhau.png"))); // NOI18N
        jmidoimatkhau.setText("Đổi Mật Khẩu");
        jmidoimatkhau.setPreferredSize(new java.awt.Dimension(213, 30));
        jmidoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmidoimatkhauActionPerformed(evt);
            }
        });
        jmHeThong.add(jmidoimatkhau);

        jmiLogOff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangxuat.png"))); // NOI18N
        jmiLogOff.setText("Đăng Xuất");
        jmiLogOff.setPreferredSize(new java.awt.Dimension(213, 30));
        jmiLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOffActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiLogOff);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thoat.png"))); // NOI18N
        jmiExit.setText("Thoát");
        jmiExit.setPreferredSize(new java.awt.Dimension(213, 30));
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiExit);

        jMenuBar2.add(jmHeThong);

        jMenu1.setBorder(null);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/quanlycoban.png"))); // NOI18N
        jMenu1.setText("Quản Lý Cơ Bản");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(145, 32));

        jmQuanLyKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmQuanLyKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmQuanLyKhoa.setText("Quản Lý Khoa");
        jmQuanLyKhoa.setPreferredSize(new java.awt.Dimension(213, 30));
        jmQuanLyKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyKhoaActionPerformed(evt);
            }
        });
        jMenu1.add(jmQuanLyKhoa);

        jmQuanLyChuyenNganh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmQuanLyChuyenNganh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        jmQuanLyChuyenNganh.setText("Quản Lý Chuyên Ngành");
        jmQuanLyChuyenNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyChuyenNganhActionPerformed(evt);
            }
        });
        jMenu1.add(jmQuanLyChuyenNganh);

        jmQuanLyLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmQuanLyLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        jmQuanLyLop.setText("Quản Lý Lớp");
        jmQuanLyLop.setPreferredSize(new java.awt.Dimension(213, 30));
        jmQuanLyLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyLopActionPerformed(evt);
            }
        });
        jMenu1.add(jmQuanLyLop);

        jMenuBar2.add(jMenu1);

        jmTacVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/quanlydaotao .png"))); // NOI18N
        jmTacVu.setText("Quản Lý Đào Tạo");
        jmTacVu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jmTacVu.setPreferredSize(new java.awt.Dimension(145, 32));

        jmiNhapSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiNhapSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmiNhapSV.setText("Quản Lý Sinh Viên");
        jmiNhapSV.setPreferredSize(new java.awt.Dimension(213, 30));
        jmiNhapSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapSVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapSV);

        jmiNhapGV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiNhapGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmiNhapGV.setText("Quản Lý Giáo Viên");
        jmiNhapGV.setPreferredSize(new java.awt.Dimension(213, 30));
        jmiNhapGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapGVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapGV);

        jmiNhapDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiNhapDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmiNhapDiem.setText("Quản Lý Điểm");
        jmiNhapDiem.setPreferredSize(new java.awt.Dimension(213, 30));
        jmiNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapDiemActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapDiem);

        jmQuanLyHocPhan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmQuanLyHocPhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmQuanLyHocPhan.setText("Quản Lý Học Phần");
        jmQuanLyHocPhan.setPreferredSize(new java.awt.Dimension(213, 30));
        jmQuanLyHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyHocPhanActionPerformed(evt);
            }
        });
        jmTacVu.add(jmQuanLyHocPhan);

        jmQuanLyMonHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmQuanLyMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next2.png"))); // NOI18N
        jmQuanLyMonHoc.setText("Quản Lý Môn Học");
        jmQuanLyMonHoc.setPreferredSize(new java.awt.Dimension(213, 30));
        jmQuanLyMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmQuanLyMonHocActionPerformed(evt);
            }
        });
        jmTacVu.add(jmQuanLyMonHoc);

        jMenuBar2.add(jmTacVu);

        jmTimKiem.setBorder(null);
        jmTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/seach.png"))); // NOI18N
        jmTimKiem.setText("Tìm Kiếm            ");
        jmTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jmTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTimKiemMouseClicked(evt);
            }
        });
        jmTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTimKiemActionPerformed(evt);
            }
        });
        jMenuBar2.add(jmTimKiem);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jtpContent.getAccessibleContext().setAccessibleName("Trang Chủ");

        setSize(new java.awt.Dimension(1122, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiNhapSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapSVActionPerformed
        // TODO add your handling code here:
        frmQuanLySinhVien sinhVien = new frmQuanLySinhVien();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Sinh Viên", sinhVien);
        sinhVien.resetForm();


    }//GEN-LAST:event_jmiNhapSVActionPerformed

    private void jmQuanLyKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyKhoaActionPerformed
        frmQuanLyKhoa khoa = new frmQuanLyKhoa();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Khoa", khoa);
        khoa.ResetForm();
       
    }//GEN-LAST:event_jmQuanLyKhoaActionPerformed

    private void jmiNhapGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapGVActionPerformed
        frmQuanLyGiaoVien giaoVien = new frmQuanLyGiaoVien();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Giáo Viên", giaoVien);
        giaoVien.resetForm();
    }//GEN-LAST:event_jmiNhapGVActionPerformed

    private void jmQuanLyChuyenNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyChuyenNganhActionPerformed
        frmQuanLyChuyenNganh chuyennganh = new frmQuanLyChuyenNganh();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Chuyên Ngành", chuyennganh);
        chuyennganh.ResetForm();
    }//GEN-LAST:event_jmQuanLyChuyenNganhActionPerformed

    private void jmQuanLyMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyMonHocActionPerformed
        frmQuanLyMonHoc monhoc = new frmQuanLyMonHoc();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Môn Học", monhoc);
        monhoc.resetForm();
    }//GEN-LAST:event_jmQuanLyMonHocActionPerformed

    private void jmiNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapDiemActionPerformed
        frmQuanLyDiem bangDiem = new frmQuanLyDiem();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Điểm", bangDiem);
        bangDiem.resetForm();
    }//GEN-LAST:event_jmiNhapDiemActionPerformed

    private void jmiLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOffActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jmiLogOffActionPerformed

    private void jmTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTimKiemActionPerformed
        TimKiem timkiem = new TimKiem();
        jtpContent.removeAll();
        jtpContent.add("Tìm Kiếm", timkiem);
    }//GEN-LAST:event_jmTimKiemActionPerformed

    private void jmTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTimKiemMouseClicked
        TimKiem timkiem = new TimKiem();
        jtpContent.removeAll();
        jtpContent.add("Tìm Kiếm", timkiem);
      
    }//GEN-LAST:event_jmTimKiemMouseClicked

    private void jmidoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmidoimatkhauActionPerformed
        DoiMatKhau ld=new DoiMatKhau();
           ld.show();
           
    }//GEN-LAST:event_jmidoimatkhauActionPerformed

    private void jmQuanLyLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyLopActionPerformed
        frmQuanLyLopHoc lophoc = new frmQuanLyLopHoc();
        jtpContent.removeAll();
        jtpContent.add("Quản Lý Lớp Học", lophoc);
        lophoc.ResetForm();
    }//GEN-LAST:event_jmQuanLyLopActionPerformed

    private void jmQuanLyHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmQuanLyHocPhanActionPerformed
       frmQuanLyHocPhan hocphan =new frmQuanLyHocPhan();
       jtpContent.removeAll();
       jtpContent.add("Quản Lý Học Phần",hocphan);
       hocphan.resetForm();
    }//GEN-LAST:event_jmQuanLyHocPhanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenu jmHeThong;
    private javax.swing.JMenuItem jmQuanLyChuyenNganh;
    private javax.swing.JMenuItem jmQuanLyHocPhan;
    private javax.swing.JMenuItem jmQuanLyKhoa;
    private javax.swing.JMenuItem jmQuanLyLop;
    private javax.swing.JMenuItem jmQuanLyMonHoc;
    private javax.swing.JMenu jmTacVu;
    private javax.swing.JMenu jmTimKiem;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogOff;
    private javax.swing.JMenuItem jmiNhapDiem;
    private javax.swing.JMenuItem jmiNhapGV;
    private javax.swing.JMenuItem jmiNhapSV;
    private javax.swing.JMenuItem jmidoimatkhau;
    private javax.swing.JTabbedPane jtpContent;
    // End of variables declaration//GEN-END:variables

    
}
